In [95]:
import numpy as np
import math
# np.set_printoptions(2)

In [ ]:
def is_u_triangular(a:np.ndarray):
    return np.allclose(a[:, :4], np.triu(a[:, :4]))
def is_singular(a:np.ndarray):
    return np.linalg.det(a)

In [127]:
def rotation_method(a:np.ndarray):
    a = a.copy()
    n, m = a.shape
    for i in range(0, m - 1):
        for j in range(i + 1, n):
            temp = math.sqrt(a[i,i] ** 2 + a[j,i] ** 2)
            cos = a[i,i] / (temp)
            sin = a[j,i] / (temp)
            a_i = cos * a[i] + sin * a[j]
            a_j = -sin * a[i] + cos * a[j]
            a[i] = a_i
            a[j] = a_j
    x = np.zeros(n)
    # TODO: add backward trace


    return a

In [128]:
test = np.array([[0.0002, 3.4, -1.8, 2.1, 2.3561],
                 [3.7, -0.9, 0.7, 5.7, 7.556],
                 [-1.9, -27, 5.3, 2.9, -3.051],
                 [18, 4.1, 7.3, -0.1, 12.334]]
                 )
res = rotation_method(test)
print(res)

[[ 1.85e+01  6.59e+00  6.71e+00  7.46e-01  1.38e+01]
 [-0.00e+00  2.67e+01 -6.14e+00 -3.05e+00  1.60e+00]
 [ 0.00e+00 -3.10e-16  1.56e+00 -5.71e+00 -5.20e+00]
 [ 0.00e+00  3.18e-16  0.00e+00 -1.68e+00 -1.68e+00]]


ValueError: setting an array element with a sequence.

In [99]:
print(res[:, :4])

[[ 1.85e+01  6.59e+00  6.71e+00  7.46e-01]
 [-0.00e+00  2.67e+01 -6.14e+00 -3.05e+00]
 [ 0.00e+00 -3.10e-16  1.56e+00 -5.71e+00]
 [ 0.00e+00  3.18e-16  0.00e+00 -1.68e+00]]
[[ 1.85e+01  6.59e+00  6.71e+00  7.46e-01  1.38e+01]
 [-0.00e+00  2.67e+01 -6.14e+00 -3.05e+00  1.60e+00]
 [ 0.00e+00 -3.10e-16  1.56e+00 -5.71e+00 -5.20e+00]
 [ 0.00e+00  3.18e-16  0.00e+00 -1.68e+00 -1.68e+00]]


In [105]:
print(res[1] == res[1, :])

[ True  True  True  True  True]
