In [104]:
import numpy as np

In [105]:
# Метод Якоби

In [106]:
def jacobi_method(
        a:np.array,
        b:np.array,
        eps:float=1e-6) -> np.array:
    if np.allclose(np.diag(a), 0):
        raise ValueError("All diagonal elements are close to zero ")
    n, m = a.shape
    A = a.copy()
    B = b.copy()
    norm = eps + 1
    current_solution = np.zeros((n, 1))
    previous_solution = B / A.diagonal()
    while norm > eps:
        current_solution = B.copy()
        for i in range(n):
            for j in range(n):
                if i != j:
                    current_solution[i][0] -= A[i,j] * previous_solution[j][0]
        current_solution /= A.diagonal()[:,np.newaxis]
        norm = np.linalg.norm(current_solution - previous_solution)
        previous_solution = current_solution

    return current_solution

In [107]:
a = np.array([[10, 1, -1],
            [1, 10, -1],
             [-1, 1, 10]], dtype="float64")
b = np.array([[11, 10, 10]], dtype="float64").T

In [108]:
jacobi_method(a, b)

array([[1.1020202],
       [0.9909091],
       [1.0111111]])

In [109]:
np.linalg.solve(a, b)

array([[1.1020202 ],
       [0.99090909],
       [1.01111111]])

# Метод минимальных невязок

In [119]:
def minimal_residuals(a:np.array, b:np.array, eps=1e-6):
    n, _ = a.shape
    prev_solution = np.ones((n, 1))
    current_solution = np.zeros((n, 1))
    r = np.ones((n, 1))
    while np.linalg.norm(r) > eps:
        r = a @ prev_solution - b
        temp = (a @ r)[:,0]
        iter_param = np.inner(temp, r[:,0]) / np.inner(temp, temp)
        current_solution = prev_solution - iter_param * r
        prev_solution = current_solution
    return current_solution

In [120]:
minimal_residuals(a, b)

array([[1.1020202 ],
       [0.99090909],
       [1.01111111]])

In [114]:
a @ Out[112] - b

array([[-0.01960784],
       [ 0.09803922],
       [-0.09803922]])